### ISSUE TITLE
Getting error while executing 'npm start'

### ISSUE THREAD

**Issue by ashish-vijay** [Jerga99/bwm-ng#20]
Following error is shown with 'npm start', front-end alone is running good with 'npm start-dev'. How to run the server?

`> y@1.0.0 start /media/ashish/New Volume/Ashish/learn/bwn/bwm-ng-master/server
> node index.js

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/media/ashish/New Volume/Ashish/learn/bwn/bwm-ng-master/server/config/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/media/ashish/New Volume/Ashish/learn/bwn/bwm-ng-master/server/index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! y@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the y@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ashish/.npm/_logs/2018-08-22T20_21_16_932Z-debug.log
ashish@hp:/media/ashish/New Volume/Ashish/learn/bwn/bwm-ng-master/server$ npm i
npm WARN y@1.0.0 No description
npm WARN y@1.0.0 No repository field.

up to date in 4.308s
found 0 vulnerabilities
`

**Comment by rahulmittal1** [comment]
how to remove abobe mentioned error??

**Comment by Jerga99** [comment]
Hello did you follow lesson how to setup completed project ? It's explained there. Actually it's very simple you just need to create dev.js file in sever/config folder and setup some variables fro Database and other services, but follow video I mentioned please.

**Comment by muneerjava17** [comment]
Hello,
Which version of the nom you are using. When I am executing the command "npm install" to install the dependencies I am getting errors. Please share with me the version of the npm and as well as other dependencies so that I can install them before executing the npm install. 
Regards,
Muneer

**Comment by muneerjava17** [comment]
Hello,
Which version of the npm you are using. When I am executing the command "npm install" to install the dependencies I am getting errors. Please share with me the version of the npm and as well as other dependencies so that I can install them before executing the npm install.
Regards,
Muneer

**Comment by hajimurtaza** [comment]
> Hello did you follow lesson how to setup completed project ? It's explained there. Actually it's very simple you just need to create dev.js file in sever/config folder and setup some variables fro Database and other services, but follow video I mentioned please.

Can i have the link where you explain environment variables?
